name: Pull request pipeline

on:
    pull_request:
        branches: ['master']

    workflow_dispatch:

jobs:
    test:
        timeout-minutes: 8
        runs-on: ubuntu-22.04
        steps:
            - uses: actions/checkout@v4
            - uses: actions/setup-node@v4
              with:
                  node-version: 21.6.1
            - name: Test
              run: |
                  npm ci
                  npm rebuild node-pty --update-binary
                  npm run test
    typecheck:
        timeout-minutes: 10
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - name: Typecheck node and web
              run: |
                  npm ci
                  npm run typecheck
    format:
        timeout-minutes: 10
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - name: Format code
              run: |
                  npm ci
                  npm run format
